[package]
name = "infosys-display"
version = "0.1.0"
authors = ["Liam Middlebrook <liammiddlebrook@gmail.com>"]

[dependencies]
chrono = "0.3"
config = "0.6"
postgres = {version = "0.14", features = ["with-chrono", "with-native-tls"]}
